### ISSUE TITLE
Missing Docs/ directory is causing setup.py to fail

### ISSUE THREAD

**Issue by blazk** [ec-jrc/pyg2p#2]
python3 branch setup.py fails with the error msg:
```
copying ./configuration/global/intertables.json -> build/bdist.linux-x86_64/egg/pyg2p/configuration/
copying ./configuration/global/parameters.json -> build/bdist.linux-x86_64/egg/pyg2p/configuration/
copying ./configuration/global/test.json -> build/bdist.linux-x86_64/egg/pyg2p/configuration/
error: can't copy './Docs/UserManual.pdf': doesn't exist or not a regular file
```

**Comment by domeniconappo** [comment]
@blazk 
Yes I just cleaned it. Could you retry please?
Docs folder is not there anymore as docs are now in README.md on repository

**Comment by blazk** [comment]
Thanks, installation worked but when I try to run 'pyg2p' I get this weird error:

```
 pyg2p
Traceback (most recent call last):
  File "/usr/local/apps/pyg2p/py3test/bin/pyg2p", line 4, in <module>
    __import__('pkg_resources').run_script('pyg2p==3.0', 'pyg2p')
  File "/usr/local/apps/python3/3.6.8-01/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/usr/local/apps/python3/3.6.8-01/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/apps/python3/3.6.8-01/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/apps/python3/3.6.8-01/lib/python3.6/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/local/apps/python3/3.6.8-01/lib/python3.6/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/apps/python3/3.6.8-01/lib/python3.6/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyg2p==3.0' distribution was not found and is required by the application
```

**Comment by blazk** [comment]
Nah, forget it, it's something to do with our python installation, when I set PYTHONPATH it works

**Comment by domeniconappo** [comment]
No probs. I had the same: It's due to a dirty state installation I guess. 
I had to remove pyg2p from site-packages and install it again. 
In development I use `pip install -e ./`.

You can do `pip install ./` so that you can remove it with `pip uninstall pyg2p`.
When this version is ready, we can use pypi repository as well.
